/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ContollerAdresse;
import controller.ControllerBanque;
import controller.ControllerEntreprise;
import database.ConnectToDataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Adresse;
import model.Banque;
import model.Entreprise;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author khairislama
 */
public class EntrepriseForm extends javax.swing.JFrame {
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    PreparedStatement pst;

    /**
     * Creates new form EntrepriseForm
     */
    public EntrepriseForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        entreprisesTable = new javax.swing.JTable();
        Description = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matriculefiscale = new javax.swing.JTextField();
        raisonsociale = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        telfixe = new javax.swing.JTextField();
        telmobile = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fax = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        siteweb = new javax.swing.JTextField();
        numerorue = new javax.swing.JTextField();
        libellerue = new javax.swing.JTextField();
        ville = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        codepostale = new javax.swing.JTextField();
        gouv = new javax.swing.JTextField();
        pays = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        banque = new javax.swing.JTextField();
        agence = new javax.swing.JTextField();
        rib = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        addbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        actualiserbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        morale = new javax.swing.JRadioButton();
        physique = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        adresseTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        banqueTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        entreprisesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Matricule fiscale", "Raison sociale", "Type", "description", "adresse", "banque", "Telf fixe", "Telf mobile", "Fax", "Email", "Site Web", "Tva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        entreprisesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entreprisesTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(entreprisesTable);

        jLabel1.setText("Matricule Fiscale");

        jLabel2.setText("Raison Sociale");

        jLabel3.setText("Type");

        jLabel4.setText("Description");

        jLabel5.setText("Telephone fixe");

        jLabel6.setText("Telephone mobile");

        jLabel7.setText("Fax");

        jLabel8.setText("Email");

        jLabel9.setText("SiteWeb");

        jLabel10.setText("Numero Rue");

        jLabel11.setText("Libelle Rue");

        jLabel12.setText("Ville");

        jLabel13.setText("Code postal");

        jLabel14.setText("Gouvernorat");

        jLabel15.setText("Pays");

        jLabel16.setText("Banque");

        jLabel17.setText("Agence");

        jLabel18.setText("RIB");

        addbtn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        addbtn.setText("Ajouter");
        addbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbtnMouseClicked(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
        });

        actualiserbtn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        actualiserbtn.setText("Actualiser");
        actualiserbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualiserbtnMouseClicked(evt);
            }
        });

        searchbtn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(actualiserbtn)
                    .addComponent(addbtn))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchbtn)
                    .addComponent(updatebtn))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(updatebtn))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualiserbtn)
                    .addComponent(searchbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        morale.setText("morale");

        physique.setText("physique");

        javax.swing.GroupLayout DescriptionLayout = new javax.swing.GroupLayout(Description);
        Description.setLayout(DescriptionLayout);
        DescriptionLayout.setHorizontalGroup(
            DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(raisonsociale)
                            .addComponent(description)
                            .addComponent(telfixe)
                            .addComponent(matriculefiscale)
                            .addComponent(telmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fax)
                            .addComponent(email))
                        .addGap(18, 18, 18))
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(morale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(physique)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)))
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel13))
                    .addComponent(jLabel14)
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(DescriptionLayout.createSequentialGroup()
                                .addComponent(libellerue, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel18))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DescriptionLayout.createSequentialGroup()
                                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(siteweb, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(numerorue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(29, 29, 29)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(agence, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(rib)
                            .addComponent(banque))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ville, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(codepostale)
                                .addComponent(pays))
                            .addComponent(gouv, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        DescriptionLayout.setVerticalGroup(
            DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescriptionLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(siteweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(banque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(numerorue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(agence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(libellerue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(rib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(physique))
                        .addGap(7, 7, 7)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DescriptionLayout.createSequentialGroup()
                                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(codepostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(gouv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(DescriptionLayout.createSequentialGroup()
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DescriptionLayout.createSequentialGroup()
                                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(matriculefiscale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addGap(17, 17, 17))
                            .addComponent(raisonsociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(morale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DescriptionLayout.createSequentialGroup()
                                .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(telfixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)))
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(telmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap())))
        );

        adresseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Libelle", "Ville", "Code postale", "Gouvernorat", "Pays", "ID entreprise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        adresseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adresseTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(adresseTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        banqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Banque", "Agence", "RIB", "Id entreprise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        banqueTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banqueTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(banqueTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 76, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Description, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbtnMouseClicked
        // TODO add your handling code here:
        String banque=this.banque.getText();
        String agence=this.agence.getText();
        int rib=Integer.valueOf(this.rib.getText());
        String id_f=matriculefiscale.getText();
        
        Banque banq=new Banque();
        banq.setBanque(banque);
        banq.setAgence(agence);
        banq.setRib(rib);
        banq.setId_e(id_f);
        ControllerBanque controllerBanque=new ControllerBanque();
        try {
                controllerBanque.AjouterBanque(banq);
        } catch (ClassNotFoundException | SQLException e3) {
                // TODO Auto-generated catch block
                e3.printStackTrace();
        }
        
        int numero_rue=Integer.valueOf(numerorue.getText());
        String libelle=libellerue.getText();
        String Ville=ville.getText();
        int code_postal=Integer.parseInt(codepostale.getText());
        String gouvernorat=gouv.getText();
        String pay=pays.getText();
        String id_e=matriculefiscale.getText();
        Adresse adresse=new Adresse();


        adresse.setNumero_rue(numero_rue);
        adresse.setVille(Ville);
        adresse.setLibelle_rue(libelle);
        adresse.setCode_postale(code_postal);
        adresse.setGouvernorat(gouvernorat);
        adresse.setPays(pay);
        adresse.setId_e(id_e);
        ContollerAdresse contollerAdresse=new ContollerAdresse();
        try {
                contollerAdresse.AjouterAdresse(adresse);
        } catch (ClassNotFoundException e2) {
                // TODO Auto-generated catch block
                e2.printStackTrace();
        } catch (SQLException e2) {
                // TODO Auto-generated catch block
                e2.printStackTrace();
        }
        
        String matricule=matriculefiscale.getText();
        String raison=raisonsociale.getText();
        String Type="physique";
        if(morale.isSelected())
               Type="morale";
        String activite=description.getText();
        int fix=Integer.valueOf(telfixe.getText());
        int mobile=Integer.valueOf(telmobile.getText());
        int fax=Integer.valueOf(this.fax.getText());
        String email=this.email.getText();
        String Web=siteweb.getText();
        int etat=-1;
        if(physique.isSelected())
               etat=1;
        else if(morale.isSelected()) {
               etat=0;
        }
        
        Entreprise entreprise=new Entreprise();
        entreprise.setMatricule_fiscale_entreprise(matricule);
        entreprise.setRaison_sociale_entreprise(raison);
        entreprise.setType_entreprise(Type);
        entreprise.setDescription_entreprise(activite);
        entreprise.setTel_fixe_entreprise(fix);
        entreprise.setTel_mobile_entreprise(mobile);
        entreprise.setTel_faxe_entreprise(fax);
        entreprise.setEmail_entreprise(email);
        entreprise.setWeb_entreprise(Web);
        entreprise.setEtat_tva(etat);
        ControllerEntreprise controllerEntreprise=new ControllerEntreprise();
        try {
            if((matricule.isEmpty()))
            {
                JOptionPane.showMessageDialog(null,"Remplir champs matricule SVP .."); 
            }else
            {
                controllerEntreprise.ajouterEntreprise(entreprise);
                JOptionPane.showMessageDialog(null, "ajouter avec success ");
            }

        } catch (ClassNotFoundException e1) {

                   e1.printStackTrace();
        } catch (SQLException e1) {

                   e1.printStackTrace();
        }
    }//GEN-LAST:event_addbtnMouseClicked

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        // TODO add your handling code here:
        String matricule=matriculefiscale.getText();
        String raison=raisonsociale.getText();
      String Type="physique";
      if(morale.isSelected())
            Type="morale";
        String activite=description.getText();
        int fix=Integer.valueOf(telfixe.getText());
        int mobile=Integer.valueOf(telmobile.getText());
        int fax=Integer.valueOf(this.fax.getText());
        String email=this.email.getText();
        String Web=siteweb.getText();
      int etat=-1;
        if(physique.isSelected())
                etat=1;
        else if(morale.isSelected()) {
                etat=0;

        }

           Entreprise entreprise=new Entreprise();
         entreprise.setMatricule_fiscale_entreprise(matricule);
        entreprise.setRaison_sociale_entreprise(raison);
        entreprise.setType_entreprise(Type);
        entreprise.setDescription_entreprise(activite);
        entreprise.setTel_fixe_entreprise(fix);
        entreprise.setTel_mobile_entreprise(mobile);
        entreprise.setTel_faxe_entreprise(fax);
        entreprise.setEmail_entreprise(email);
        entreprise.setWeb_entreprise(Web);
        entreprise.setEtat_tva(etat);

        ControllerEntreprise controllerEntreprise=new ControllerEntreprise();
        controllerEntreprise.modifierEntreprise(entreprise);
    }//GEN-LAST:event_updatebtnMouseClicked

    private void searchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbtnMouseClicked
        // TODO add your handling code here:
        try {
        Connection con=ConnectToDataBase.getConnection();
        pst=con.prepareStatement("SELECT * FROM entreprise where matricule = ?");
        pst.setString(1,matriculefiscale.getText());
        rs=pst.executeQuery();

                entreprisesTable.setModel(DbUtils.resultSetToTableModel(rs));


        } catch (ClassNotFoundException | SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
        }	
        try {
                Connection con=ConnectToDataBase.getConnection();
                pst=con.prepareStatement("SELECT * FROM banque where id_e = ?");
                pst.setString(1,matriculefiscale.getText());
                rs=pst.executeQuery();

                        banqueTable.setModel(DbUtils.resultSetToTableModel(rs));


        } catch (ClassNotFoundException | SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
        }	
        try {
                Connection con=ConnectToDataBase.getConnection();
                pst=con.prepareStatement("SELECT * FROM adresse where id_e = ?");
                pst.setString(1,matriculefiscale.getText());
                rs=pst.executeQuery();

                        adresseTable.setModel(DbUtils.resultSetToTableModel(rs));


        } catch (ClassNotFoundException | SQLException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
        }	
    }//GEN-LAST:event_searchbtnMouseClicked

    private void actualiserbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualiserbtnMouseClicked
        // TODO add your handling code here:
        try {
            con=ConnectToDataBase.getConnection();
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM entreprise");
            entreprisesTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (ClassNotFoundException | SQLException e) {
            e.printStackTrace();
        }
        try {
                con=ConnectToDataBase.getConnection();
                st=con.createStatement();
                rs=st.executeQuery("SELECT `numero`, `libelle`, `ville`, `codepostal`, `gouvernorat`, `pays`, `id_e` FROM adresse");
                adresseTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e) {

        }
        try {
                con=ConnectToDataBase.getConnection();
                st=con.createStatement();
                rs=st.executeQuery("SELECT `banque`, `agence`, `rib`, `id_e` FROM banque");
                banqueTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e) {

        }
    }//GEN-LAST:event_actualiserbtnMouseClicked

    private void entreprisesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entreprisesTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) entreprisesTable.getModel();
        int index=entreprisesTable.getSelectedRow();
        matriculefiscale.setText(model.getValueAt(index,1).toString());
        raisonsociale.setText(model.getValueAt(index,2).toString());
        description.setText(model.getValueAt(index,4).toString());
        telfixe.setText(model.getValueAt(index,5).toString());
        telmobile.setText(model.getValueAt(index,6).toString());
        fax.setText(model.getValueAt(index,7).toString());
        email.setText(model.getValueAt(index,8).toString());
        siteweb.setText(model.getValueAt(index,9).toString()) ;
    }//GEN-LAST:event_entreprisesTableMouseClicked

    private void adresseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adresseTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)adresseTable.getModel();
        int index=adresseTable.getSelectedRow();
        numerorue.setText(model.getValueAt(index,0).toString());
        libellerue.setText(model.getValueAt(index,1).toString());
        ville.setText(model.getValueAt(index,2).toString());
        codepostale.setText(model.getValueAt(index,3).toString());
        gouv.setText(model.getValueAt(index,4).toString());
        pays.setText(model.getValueAt(index,5).toString());
    }//GEN-LAST:event_adresseTableMouseClicked

    private void banqueTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banqueTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)banqueTable.getModel();
            int index=banqueTable.getSelectedRow();
            banque.setText(model.getValueAt(index,0).toString());
        agence.setText(model.getValueAt(index,1).toString());
        rib.setText(model.getValueAt(index,2).toString());
    }//GEN-LAST:event_banqueTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntrepriseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntrepriseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntrepriseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntrepriseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntrepriseForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Description;
    private javax.swing.JButton actualiserbtn;
    private javax.swing.JButton addbtn;
    private javax.swing.JTable adresseTable;
    private javax.swing.JTextField agence;
    private javax.swing.JTextField banque;
    private javax.swing.JTable banqueTable;
    private javax.swing.JTextField codepostale;
    private javax.swing.JTextField description;
    private javax.swing.JTextField email;
    private javax.swing.JTable entreprisesTable;
    private javax.swing.JTextField fax;
    private javax.swing.JTextField gouv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField libellerue;
    private javax.swing.JTextField matriculefiscale;
    private javax.swing.JRadioButton morale;
    private javax.swing.JTextField numerorue;
    private javax.swing.JTextField pays;
    private javax.swing.JRadioButton physique;
    private javax.swing.JTextField raisonsociale;
    private javax.swing.JTextField rib;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField siteweb;
    private javax.swing.JTextField telfixe;
    private javax.swing.JTextField telmobile;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField ville;
    // End of variables declaration//GEN-END:variables
}
