/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ContollerAdresse;
import controller.ControllerBanque;
import controller.ControllerFornisseur;
import database.ConnectToDataBase;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Adresse;
import model.Banque;
import model.Fournisseur;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author khairislama
 */
public class FournisseurForm extends javax.swing.JFrame {
    
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    PreparedStatement pst;

    /**
     * Creates new form FournisseurForm
     */
    public FournisseurForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fournisseurTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codefournisseur = new javax.swing.JTextField();
        matriculefiscale = new javax.swing.JTextField();
        raisonsociale = new javax.swing.JTextField();
        telfixe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        telmobile = new javax.swing.JTextField();
        morale = new javax.swing.JRadioButton();
        physique = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        fax = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        siteweb = new javax.swing.JTextField();
        numerorue = new javax.swing.JTextField();
        numerolibelle = new javax.swing.JTextField();
        ville = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        codepostale = new javax.swing.JTextField();
        gouv = new javax.swing.JTextField();
        pays = new javax.swing.JTextField();
        banque = new javax.swing.JTextField();
        agence = new javax.swing.JTextField();
        rib = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        ajouterbtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        actualiserbtn = new javax.swing.JButton();
        supprimerbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();
        tva = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        adresseTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        banqueTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fournisseurTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CodeClient", "Matricule fiscale", "Raison sociale", "Type", "Adresse", "Banque", "Tel fixe", "Tel mobile", "Fax", "email", "web", "tva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        fournisseurTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fournisseurTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fournisseurTable);

        jLabel1.setText("Code Fournisseur");

        jLabel2.setText("Matricule fiscale");

        jLabel3.setText("Raison sociale");

        jLabel4.setText("Type");

        jLabel5.setText("Telf fixe");

        codefournisseur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codefournisseurActionPerformed(evt);
            }
        });

        jLabel6.setText("Telf mobile");

        morale.setText("morale");

        physique.setText("Physique");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telfixe))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telmobile))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(codefournisseur))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(matriculefiscale, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(morale)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(physique)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(raisonsociale))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codefournisseur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(matriculefiscale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(raisonsociale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(morale)
                        .addComponent(physique)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telfixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telmobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel7.setText("Fax");

        jLabel8.setText("email");

        jLabel9.setText("Site web");

        jLabel10.setText("Numero rue");

        jLabel11.setText("numero libelle");

        jLabel12.setText("Ville");

        jLabel13.setText("Code postale");

        jLabel14.setText("Gouvernorat");

        jLabel15.setText("Pays");

        jLabel16.setText("Banque");

        jLabel17.setText("Agence");

        jLabel18.setText("RIB");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pays))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gouv))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agence))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(banque))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rib))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codepostale, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(codepostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(gouv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(banque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(agence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ajouterbtn.setText("Ajouter");
        ajouterbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajouterbtnMouseClicked(evt);
            }
        });

        updatebtn.setText("update");
        updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatebtnMouseClicked(evt);
            }
        });

        actualiserbtn.setText("actualiser");
        actualiserbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actualiserbtnMouseClicked(evt);
            }
        });

        supprimerbtn.setText("supprimer");
        supprimerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                supprimerbtnMouseClicked(evt);
            }
        });

        searchbtn.setText("search");
        searchbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbtnMouseClicked(evt);
            }
        });

        tva.setText("TVA");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(updatebtn)
                        .addComponent(actualiserbtn)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchbtn)
                            .addComponent(supprimerbtn)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(ajouterbtn))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(tva)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(tva)
                .addGap(47, 47, 47)
                .addComponent(ajouterbtn)
                .addGap(18, 18, 18)
                .addComponent(updatebtn)
                .addGap(18, 18, 18)
                .addComponent(actualiserbtn)
                .addGap(18, 18, 18)
                .addComponent(supprimerbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fax, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(email)
                    .addComponent(siteweb)
                    .addComponent(numerorue)
                    .addComponent(numerolibelle)
                    .addComponent(ville))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siteweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerorue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numerolibelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        adresseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Libelle", "Ville", "Code postale", "Gouvernorat", "Pays", "ID entreprise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        adresseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adresseTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(adresseTable);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );

        banqueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Banque", "Agence", "RIB", "Id entreprise"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        banqueTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                banqueTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(banqueTable);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codefournisseurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codefournisseurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codefournisseurActionPerformed

    private void ajouterbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajouterbtnMouseClicked
        // TODO add your handling code here:
        String code=codefournisseur.getText();
        String matriculeclient=matriculefiscale.getText();
        String raison=raisonsociale.getText();
        String type="physique";
        if(morale.isSelected())
        type="morale";
        int fix=Integer.valueOf(telfixe.getText());
        int mobile=Integer.valueOf(telmobile.getText());
        int fax=Integer.valueOf(this.fax.getText());
        String email1=email.getText();
        String Web=siteweb.getText();
        int etat=-1;
        if(tva.isSelected())
        etat=1;
        else
        etat=0;

        Fournisseur c=new Fournisseur();
        c.setCode_fornisseur_client(code);
        c.setMatricule_fiscale_fornisseur_client(matriculeclient);
        c.setRaison_sociale_fornisseur_client(raison);
        c.setType_fornisseur_client(type);
        c.setTel_fixe_fornisseur_client(fix);
        c.setTel_mobile_fornisseur_client(mobile);
        c.setTel_faxe_fornisseur_client(fax);
        c.setEmail_fornisseur_client(email1);
        c.setWeb_fornisseur_client(Web);
        ControllerFornisseur cl=new ControllerFornisseur();
        if((matriculeclient.isEmpty()))
        {
            JOptionPane.showMessageDialog(null,"Remplir champs matricule SVP ..");
        }else {
            cl.verifier(c, matriculeclient);
        }

        int numero_rue=Integer.valueOf(numerorue.getText());
        String libelle=numerolibelle.getText();
        String Ville=ville.getText();
        int code_postal=Integer.valueOf(codepostale.getText());
        String gouvernorat=gouv.getText();
        String pay=pays.getText();
        String id_e=codefournisseur.getText();
        Adresse adresse=new Adresse();

        adresse.setNumero_rue(numero_rue);
        adresse.setVille(Ville);
        adresse.setLibelle_rue(libelle);
        adresse.setCode_postale(code_postal);
        adresse.setGouvernorat(gouvernorat);
        adresse.setPays(pay);
        adresse.setId_e(id_e);
        ContollerAdresse contollerAdresse=new ContollerAdresse();
        try {
            contollerAdresse.AjouterAdresse(adresse);
        } catch (ClassNotFoundException e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        } catch (SQLException e2) {
            // TODO Auto-generated catch block
            e2.printStackTrace();
        }

        String banquef=banque.getText();
        String agencef=agence.getText();
        String id_ff=codefournisseur.getText();
        int ripf=Integer.parseInt(rib.getText());

        Banque bf=new Banque();
        bf.setBanque(banquef);
        bf.setAgence(agencef);
        bf.setRib(ripf);
        bf.setId_e(id_ff);
        ControllerBanque cb=new ControllerBanque();
        try {
            cb.AjouterBanque(bf);

        } catch (ClassNotFoundException | SQLException e1) {
            // TODO Auto-generated catch block
            //e1.printStackTrace();
        }
    }//GEN-LAST:event_ajouterbtnMouseClicked

    private void updatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatebtnMouseClicked
        // TODO add your handling code here:
        String code=email.getText();
        String matricule=matriculefiscale.getText();
        String raison=raisonsociale.getText();
        String type="physique";
        if(morale.isSelected())
        type="morale";
        int fix=Integer.valueOf(telfixe.getText());
        int mobile=Integer.valueOf(telmobile.getText());
        int fax=Integer.valueOf(this.fax.getText());
        String email=this.email.getText();
        String Web=siteweb.getText();
        int etat=-1;
        if(tva.isSelected())
        etat=1;
        else
        etat=0;

        Fournisseur c=new Fournisseur();
        c.setCode_fornisseur_client(code);
        c.setMatricule_fiscale_fornisseur_client(matricule);
        c.setRaison_sociale_fornisseur_client(raison);
        c.setType_fornisseur_client(type);
        c.setTel_fixe_fornisseur_client(fix);
        c.setTel_mobile_fornisseur_client(mobile);
        c.setTel_faxe_fornisseur_client(fax);
        c.setEmail_fornisseur_client(email);
        c.setWeb_fornisseur_client(Web);
        ControllerFornisseur cl=new ControllerFornisseur();
        cl.modifierFornisseur(c);
        JOptionPane.showMessageDialog(null, "Modifer avec succeesss");
    }//GEN-LAST:event_updatebtnMouseClicked

    private void actualiserbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actualiserbtnMouseClicked
        // TODO add your handling code here:
        try {
            con=ConnectToDataBase.getConnection();
            st=con.createStatement();
            rs=st.executeQuery("SELECT * FROM forniseur");
            fournisseurTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e) {

        }
        try {
                con=ConnectToDataBase.getConnection();
                st=con.createStatement();
                rs=st.executeQuery("SELECT `numero`, `libelle`, `ville`, `codepostal`, `gouvernorat`, `pays`, `id_e` FROM adresse");
                adresseTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e) {

        }
        try {
                con=ConnectToDataBase.getConnection();
                st=con.createStatement();
                rs=st.executeQuery("SELECT `banque`, `agence`, `rib`, `id_e` FROM banque");
                banqueTable.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e) {

        }
    }//GEN-LAST:event_actualiserbtnMouseClicked

    private void supprimerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supprimerbtnMouseClicked
        // TODO add your handling code here:
        try {
            String code=codefournisseur.getText();
            Fournisseur c=new Fournisseur();
            c.setCode_fornisseur_client(code);
            ControllerFornisseur cl=new ControllerFornisseur();
            cl.DeleteFornisseur(c);
        } catch (Exception e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }
    }//GEN-LAST:event_supprimerbtnMouseClicked

    private void fournisseurTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fournisseurTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) fournisseurTable.getModel();
        int index=fournisseurTable.getSelectedRow();
        codefournisseur.setText(model.getValueAt(index,0).toString());
        matriculefiscale.setText(model.getValueAt(index,1).toString());
        raisonsociale.setText(model.getValueAt(index,2).toString());
        telfixe.setText(model.getValueAt(index,4).toString());
        telmobile.setText(model.getValueAt(index,5).toString());
        fax.setText(model.getValueAt(index,6).toString());
        email.setText(model.getValueAt(index,7).toString());
        siteweb.setText(model.getValueAt(index,8).toString()) ;
    }//GEN-LAST:event_fournisseurTableMouseClicked

    private void searchbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbtnMouseClicked
        // TODO add your handling code here:
        try {
                Connection con=ConnectToDataBase.getConnection();
                pst=con.prepareStatement("SELECT * FROM forniseur where matricule = ?");
                pst.setString(1,matriculefiscale.getText());
                rs=pst.executeQuery();

                        fournisseurTable.setModel(DbUtils.resultSetToTableModel(rs));


        } catch (ClassNotFoundException | SQLException ex) {
                // TODO Auto-generated catch block
                ex.printStackTrace();
        }	
        try {
                Connection con=ConnectToDataBase.getConnection();
                pst=con.prepareStatement("SELECT `banque`, `agence`, `rib` FROM `banque` where id_e = ?");
                pst.setString(1,matriculefiscale.getText());
                rs=pst.executeQuery();

                        banqueTable.setModel(DbUtils.resultSetToTableModel(rs));


        } catch (ClassNotFoundException | SQLException ex) {
                // TODO Auto-generated catch block
                ex.printStackTrace();
        }	
        try {
                Connection con=ConnectToDataBase.getConnection();
                pst=con.prepareStatement("SELECT  `numero`, `libelle`, `ville`, `codepostal`, `gouvernorat`,`pays` FROM adresse where id_e = ?");
                pst.setString(1,matriculefiscale.getText());
                rs=pst.executeQuery();

                        adresseTable.setModel(DbUtils.resultSetToTableModel(rs));


        } catch (ClassNotFoundException | SQLException ex) {
                // TODO Auto-generated catch block
                ex.printStackTrace();
        }
    }//GEN-LAST:event_searchbtnMouseClicked

    private void adresseTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adresseTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)adresseTable.getModel();
        int index=adresseTable.getSelectedRow();
        numerorue.setText(model.getValueAt(index,0).toString());
        numerolibelle.setText(model.getValueAt(index,1).toString());
        ville.setText(model.getValueAt(index,2).toString());
        codepostale.setText(model.getValueAt(index,3).toString());
        gouv.setText(model.getValueAt(index,4).toString());
        pays.setText(model.getValueAt(index,5).toString());
    }//GEN-LAST:event_adresseTableMouseClicked

    private void banqueTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banqueTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel)banqueTable.getModel();
            int index=banqueTable.getSelectedRow();
            banque.setText(model.getValueAt(index,0).toString());
        agence.setText(model.getValueAt(index,1).toString());
        rib.setText(model.getValueAt(index,2).toString());
    }//GEN-LAST:event_banqueTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FournisseurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FournisseurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FournisseurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FournisseurForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FournisseurForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualiserbtn;
    private javax.swing.JTable adresseTable;
    private javax.swing.JTextField agence;
    private javax.swing.JButton ajouterbtn;
    private javax.swing.JTextField banque;
    private javax.swing.JTable banqueTable;
    private javax.swing.JTextField codefournisseur;
    private javax.swing.JTextField codepostale;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fax;
    private javax.swing.JTable fournisseurTable;
    private javax.swing.JTextField gouv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField matriculefiscale;
    private javax.swing.JRadioButton morale;
    private javax.swing.JTextField numerolibelle;
    private javax.swing.JTextField numerorue;
    private javax.swing.JTextField pays;
    private javax.swing.JRadioButton physique;
    private javax.swing.JTextField raisonsociale;
    private javax.swing.JTextField rib;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField siteweb;
    private javax.swing.JButton supprimerbtn;
    private javax.swing.JTextField telfixe;
    private javax.swing.JTextField telmobile;
    private javax.swing.JRadioButton tva;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField ville;
    // End of variables declaration//GEN-END:variables
}
